name:                do-notation
version:             0.1.0.1
github:              "isovector/do-notation"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generalize do-notation to work on monads and indexed monads simultaneously.
category:            Language

description:         Please see the README on GitHub at <https://github.com/isovector/do-notation#readme>

dependencies:
- base >= 4.7 && < 5
- indexed

library:
  source-dirs: src

tests:
  do-notation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - do-notation
